### ISSUE TITLE
Missing Script

### ISSUE THREAD

**Issue by codemeleon** [jessiewu/bacterialGWAS#3]
Where is do_logreg_chw.R script?

**Comment by jessiewu** [comment]
Hi,

I have got in touch with the author of the pan-genome pipeline. The do_logreg_chw.R script now in pangenomeGWAS folder should be what you are looking for.

In the future, please could you post any queries or issues to

https://groups.google.com/forum/#!forum/bacterialgwas-users 

instead of the github issue database? The reason is because there could be other users who might also have the same queries but don't have a github account (as they don't need to write code regularly). It would also be easier for us to manage things if we just keep the github issue database for developers only. Sorry for the fuss and thanks again for your interest.

Kind regards,

Jessie

**Comment by codemeleon** [comment]
Thank you. 

From now on, I put my queries on provided google group link.
